name: Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull image - docker
        run: docker pull docker

      - name: run image - docker
        run: docker run docker
