name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: ahmadaidin/ginplating/test-action@v1
        with:
          name: Aidin
